global using NUnit.Framework;
global using DataAccesLayer.Datas;
global using Microsoft.EntityFrameworkCore;
global using DataAccesLayer.Models;
global using DataAccesLayer.Repositories;
global using DataAccesLayer.Interfaces;
global using BusinessLogicLayer.Services;
global using AutoMapper;
global using DTO;